export type Coalition = "afghan" | "british" | "russian" | "none";
export type Suit = "political" | "intelligence" | "economic" | "military";
export type Region = "kabul" | "kandahar" | "punjab" | "herat" | "persia" | "transcaspia";

export type ActionIcon = "tax" | "gift" | "build" | "move" | "battle" | "betray" | "spy";

export type CardEffectHook =
  | "on_play"
  | "on_buy"
  | "on_turn_start"
  | "on_battle"
  | "on_betray"
  | "on_dominance_check"
  | "battle_resolution"
  | "battle_protection"
  | "betray_protection"
  | "army_movement"
  | "spy_movement"
  | "play_card"
  | "purchase"
  | "build"
  | "tax"
  | "hostage"
  | "favored_suit"
  | "start_of_turn"
  | "dominance_check";

export interface CardEffect {
  id: string;
  hook: CardEffectHook;
  ruleText: string;
}

export interface CardDefinition {
  id: string;
  name: string;
  suit: Suit;
  region: Region;
  coalition: Coalition;
  rank: number;
  stars: number;
  isPatriot: boolean;
  actionIcons: ActionIcon[];
  effects: CardEffect[];
}

export const REGION_BORDERS: Array<[Region, Region]> = [
  ["herat", "persia"],
  ["herat", "transcaspia"],
  ["herat", "kabul"],
  ["herat", "kandahar"],
  ["kabul", "transcaspia"],
  ["kabul", "kandahar"],
  ["kabul", "punjab"],
  ["kandahar", "punjab"],
  ["persia", "transcaspia"],
];

const borderSet = new Set<string>();
for (const [a, b] of REGION_BORDERS) {
  borderSet.add(`${a}:${b}`);
  borderSet.add(`${b}:${a}`);
}

export function areRegionsAdjacent(a: Region, b: Region): boolean {
  return borderSet.has(`${a}:${b}`);
}

export function getAdjacentRegions(region: Region): Region[] {
  const adjacent: Region[] = [];
  for (const [a, b] of REGION_BORDERS) {
    if (a === region) adjacent.push(b);
    else if (b === region) adjacent.push(a);
  }
  return adjacent;
}


// Full Pax Pamir 2nd Edition court card deck (100 cards).
// Data sourced from the BGA implementation by Frans Bongers.
export const CARD_LIBRARY: CardDefinition[] = [
  {
    id: "card_1",
    name: "Mohan Lal",
    suit: "intelligence",
    region: "kabul",
    coalition: "none",
    rank: 3,
    stars: 0,
    isPatriot: false,
    actionIcons: ["move"],
    effects: [
      {
        id: "indispensable_advisors",
        hook: "battle_resolution",
        ruleText: "Your spies cannot be removed in battles with other spies.",
      },
    ],
  },
  {
    id: "card_2",
    name: "Jan-Fishan Khan",
    suit: "intelligence",
    region: "kabul",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle", "move"],
    effects: [],
  },
  {
    id: "card_3",
    name: "Prince Akbar Khan",
    suit: "intelligence",
    region: "kabul",
    coalition: "afghan",
    rank: 2,
    stars: 0,
    isPatriot: true,
    actionIcons: ["battle"],
    effects: [
      {
        id: "insurrection",
        hook: "dominance_check",
        ruleText: "After resolving a Dominance Check, place two Afghan armies in Kabul.",
      },
    ],
  },
  {
    id: "card_4",
    name: "Charles Stoddart",
    suit: "intelligence",
    region: "kabul",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["gift", "move"],
    effects: [],
  },
  {
    id: "card_5",
    name: "Shah Shujah Durrani",
    suit: "political",
    region: "kabul",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["build"],
    effects: [
      {
        id: "claim_of_ancient_lineage",
        hook: "tax",
        ruleText: "When you take the tax action, act as if you rule every region.",
      },
    ],
  },
  {
    id: "card_6",
    name: "Aminullah Khan Logari",
    suit: "political",
    region: "kabul",
    coalition: "afghan",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["build", "battle"],
    effects: [],
  },
  {
    id: "card_7",
    name: "Dost Mohammad",
    suit: "political",
    region: "kabul",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: [],
    effects: [],
  },
  {
    id: "card_8",
    name: "Kabul Bazaar",
    suit: "economic",
    region: "kabul",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax"],
    effects: [],
  },
  {
    id: "card_9",
    name: "Afghan Handicrafts",
    suit: "economic",
    region: "kabul",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "move"],
    effects: [],
  },
  {
    id: "card_10",
    name: "Balkh Arsenic Mine",
    suit: "economic",
    region: "kabul",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["build", "betray"],
    effects: [],
  },
  {
    id: "card_11",
    name: "Lapis Lazuli Mine",
    suit: "economic",
    region: "kabul",
    coalition: "afghan",
    rank: 2,
    stars: 0,
    isPatriot: true,
    actionIcons: ["tax", "gift"],
    effects: [],
  },
  {
    id: "card_12",
    name: "City of Ghazni",
    suit: "economic",
    region: "kabul",
    coalition: "none",
    rank: 3,
    stars: 0,
    isPatriot: false,
    actionIcons: ["gift"],
    effects: [],
  },
  {
    id: "card_13",
    name: "Ghilzai Nomads",
    suit: "economic",
    region: "kabul",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "move"],
    effects: [],
  },
  {
    id: "card_14",
    name: "Money Lenders",
    suit: "economic",
    region: "kabul",
    coalition: "none",
    rank: 2,
    stars: 1,
    isPatriot: false,
    actionIcons: ["gift", "build"],
    effects: [],
  },
  {
    id: "card_15",
    name: "Durrani Royal Guard",
    suit: "military",
    region: "kabul",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["betray"],
    effects: [
      {
        id: "bodyguards",
        hook: "betray_protection",
        ruleText: "Your political cards cannot be targets of the betray action.",
      },
    ],
  },
  {
    id: "card_16",
    name: "Bala Hissar",
    suit: "military",
    region: "kabul",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "betray"],
    effects: [],
  },
  {
    id: "card_17",
    name: "Citadel of Ghazni",
    suit: "military",
    region: "kabul",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["build"],
    effects: [
      {
        id: "citadel_kabul",
        hook: "battle_protection",
        ruleText: "Your tribes in Kabul cannot be attacked.",
      },
    ],
  },
  {
    id: "card_18",
    name: "Harry Flashman",
    suit: "intelligence",
    region: "punjab",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["gift", "betray"],
    effects: [],
  },
  {
    id: "card_19",
    name: "Eldred Pottinger",
    suit: "intelligence",
    region: "punjab",
    coalition: "british",
    rank: 2,
    stars: 0,
    isPatriot: true,
    actionIcons: ["move", "betray"],
    effects: [],
  },
  {
    id: "card_20",
    name: "Henry Rawlinson",
    suit: "intelligence",
    region: "punjab",
    coalition: "british",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["gift", "move"],
    effects: [],
  },
  {
    id: "card_21",
    name: "Alexander Burnes",
    suit: "intelligence",
    region: "punjab",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["move"],
    effects: [
      {
        id: "strange_bedfellows",
        hook: "spy_movement",
        ruleText: "For spy travel, you treat cards that share a region as adjacent.",
      },
    ],
  },
  {
    id: "card_22",
    name: "George Hayward",
    suit: "intelligence",
    region: "punjab",
    coalition: "british",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["move", "gift"],
    effects: [],
  },
  {
    id: "card_23",
    name: "Henry Pottinger",
    suit: "intelligence",
    region: "punjab",
    coalition: "british",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["battle", "move"],
    effects: [],
  },
  {
    id: "card_24",
    name: "Ranjit Singh",
    suit: "political",
    region: "punjab",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["betray"],
    effects: [
      {
        id: "civil_service_reforms",
        hook: "hostage",
        ruleText: "You do not pay bribes when taking hostage actions.",
      },
    ],
  },
  {
    id: "card_25",
    name: "Josiah Harlan",
    suit: "political",
    region: "punjab",
    coalition: "afghan",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["tax"],
    effects: [],
  },
  {
    id: "card_26",
    name: "Paolo Avitabile",
    suit: "political",
    region: "punjab",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["betray"],
    effects: [],
  },
  {
    id: "card_27",
    name: "Maqpon Dynasty",
    suit: "political",
    region: "punjab",
    coalition: "none",
    rank: 1,
    stars: 1,
    isPatriot: false,
    actionIcons: ["build"],
    effects: [],
  },
  {
    id: "card_28",
    name: "Anarkali Bazaar",
    suit: "economic",
    region: "punjab",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "build"],
    effects: [],
  },
  {
    id: "card_29",
    name: "Khyber Pass",
    suit: "economic",
    region: "punjab",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "move"],
    effects: [],
  },
  {
    id: "card_30",
    name: "Sikh Merchants in Lahore",
    suit: "economic",
    region: "punjab",
    coalition: "none",
    rank: 1,
    stars: 1,
    isPatriot: false,
    actionIcons: ["tax", "gift"],
    effects: [],
  },
  {
    id: "card_31",
    name: "Company Weapons",
    suit: "military",
    region: "punjab",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "betray"],
    effects: [],
  },
  {
    id: "card_32",
    name: "Army of the Indus",
    suit: "military",
    region: "punjab",
    coalition: "british",
    rank: 3,
    stars: 0,
    isPatriot: true,
    actionIcons: ["move"],
    effects: [],
  },
  {
    id: "card_33",
    name: "Zorawar Singh Kahluria",
    suit: "military",
    region: "punjab",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle", "gift"],
    effects: [],
  },
  {
    id: "card_34",
    name: "Sindhi Warriors",
    suit: "military",
    region: "punjab",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle", "move", "betray"],
    effects: [],
  },
  {
    id: "card_35",
    name: "Hari Singh Nalwa",
    suit: "military",
    region: "punjab",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle", "move"],
    effects: [],
  },
  {
    id: "card_36",
    name: "Bengal Native Infantry",
    suit: "military",
    region: "punjab",
    coalition: "british",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["battle", "betray"],
    effects: [],
  },
  {
    id: "card_37",
    name: "Seaforth Highlanders",
    suit: "military",
    region: "punjab",
    coalition: "british",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["battle", "move"],
    effects: [],
  },
  {
    id: "card_38",
    name: "Akali Sikhs",
    suit: "military",
    region: "punjab",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle"],
    effects: [],
  },
  {
    id: "card_39",
    name: "William Moorcroft",
    suit: "intelligence",
    region: "kandahar",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["move", "battle"],
    effects: [],
  },
  {
    id: "card_40",
    name: "William Hay Macnaghten",
    suit: "intelligence",
    region: "kandahar",
    coalition: "british",
    rank: 2,
    stars: 1,
    isPatriot: true,
    actionIcons: ["tax", "move"],
    effects: [],
  },
  {
    id: "card_41",
    name: "Charles Masson",
    suit: "intelligence",
    region: "kandahar",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["build"],
    effects: [
      {
        id: "safe_house",
        hook: "battle_resolution",
        ruleText: "When another player removes your spy in battle, you may place it on this card instead.",
      },
    ],
  },
  {
    id: "card_42",
    name: "Barakzai Sadars",
    suit: "political",
    region: "kandahar",
    coalition: "afghan",
    rank: 1,
    stars: 1,
    isPatriot: true,
    actionIcons: ["build"],
    effects: [
      {
        id: "charismatic_courtiers",
        hook: "play_card",
        ruleText: "You do not pay bribes when playing cards.",
      },
    ],
  },
  {
    id: "card_43",
    name: "Giljee Nobles",
    suit: "political",
    region: "kandahar",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle"],
    effects: [
      {
        id: "blackmail_kandahar",
        hook: "start_of_turn",
        ruleText: "At start of turn, you may place a spy on any Kandahar court card without a spy.",
      },
    ],
  },
  {
    id: "card_44",
    name: "Baluchi Chiefs",
    suit: "political",
    region: "kandahar",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["build", "tax"],
    effects: [],
  },
  {
    id: "card_45",
    name: "Haji Khan Kakar",
    suit: "political",
    region: "kandahar",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["betray", "gift"],
    effects: [],
  },
  {
    id: "card_46",
    name: "Bank",
    suit: "economic",
    region: "kandahar",
    coalition: "none",
    rank: 2,
    stars: 1,
    isPatriot: false,
    actionIcons: ["gift"],
    effects: [],
  },
  {
    id: "card_47",
    name: "Bolan Pass",
    suit: "economic",
    region: "kandahar",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["gift", "move"],
    effects: [],
  },
  {
    id: "card_48",
    name: "Fruit markets",
    suit: "economic",
    region: "kandahar",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["move", "build"],
    effects: [],
  },
  {
    id: "card_49",
    name: "Kandahari Markets",
    suit: "economic",
    region: "kandahar",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "build"],
    effects: [],
  },
  {
    id: "card_50",
    name: "British Regulars",
    suit: "military",
    region: "kandahar",
    coalition: "british",
    rank: 2,
    stars: 0,
    isPatriot: true,
    actionIcons: ["battle", "move"],
    effects: [],
  },
  {
    id: "card_51",
    name: "Sir John Keane",
    suit: "military",
    region: "kandahar",
    coalition: "british",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["battle"],
    effects: [
      {
        id: "indian_supplies",
        hook: "army_movement",
        ruleText: "Your armies may move without a road.",
      },
    ],
  },
  {
    id: "card_52",
    name: "Pashtun Mercenary",
    suit: "military",
    region: "kandahar",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle", "tax"],
    effects: [],
  },
  {
    id: "card_53",
    name: "Jezail Sharpshooters",
    suit: "military",
    region: "kandahar",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["betray"],
    effects: [],
  },
  {
    id: "card_54",
    name: "Herati Bandits",
    suit: "intelligence",
    region: "herat",
    coalition: "none",
    rank: 1,
    stars: 1,
    isPatriot: false,
    actionIcons: ["tax"],
    effects: [
      {
        id: "blackmail_herat",
        hook: "start_of_turn",
        ruleText: "At start of turn, you may place a spy on any Herat court card without a spy.",
      },
    ],
  },
  {
    id: "card_55",
    name: "Hazara Chiefs",
    suit: "political",
    region: "herat",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle", "tax", "move"],
    effects: [],
  },
  {
    id: "card_56",
    name: "Yar Mohammad Alikozai",
    suit: "political",
    region: "herat",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["betray"],
    effects: [
      {
        id: "well_connected",
        hook: "spy_movement",
        ruleText: "Your spies may double their distance moved when using a move action.",
      },
    ],
  },
  {
    id: "card_57",
    name: "Exiled Durrani Nobility",
    suit: "political",
    region: "herat",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["betray", "move"],
    effects: [],
  },
  {
    id: "card_58",
    name: "Ishaqzai Chiefs",
    suit: "political",
    region: "herat",
    coalition: "afghan",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["gift", "build"],
    effects: [],
  },
  {
    id: "card_59",
    name: "Tajik Warband",
    suit: "military",
    region: "herat",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["betray", "battle"],
    effects: [],
  },
  {
    id: "card_60",
    name: "Nomadic Warlord",
    suit: "military",
    region: "herat",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "gift", "battle"],
    effects: [],
  },
  {
    id: "card_61",
    name: "Karakul Sheep",
    suit: "economic",
    region: "herat",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax"],
    effects: [],
  },
  {
    id: "card_62",
    name: "Qanat System",
    suit: "economic",
    region: "herat",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["gift", "build"],
    effects: [],
  },
  {
    id: "card_63",
    name: "Farah Road",
    suit: "economic",
    region: "herat",
    coalition: "none",
    rank: 3,
    stars: 0,
    isPatriot: false,
    actionIcons: ["move"],
    effects: [],
  },
  {
    id: "card_64",
    name: "Opium Fields",
    suit: "economic",
    region: "herat",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax"],
    effects: [],
  },
  {
    id: "card_65",
    name: "Minaret of Jam",
    suit: "economic",
    region: "herat",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle", "tax", "move"],
    effects: [],
  },
  {
    id: "card_66",
    name: "Baluchi Smugglers",
    suit: "economic",
    region: "herat",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle"],
    effects: [
      {
        id: "herat_influence",
        hook: "purchase",
        ruleText: "You do not pay for Herat cards in the market.",
      },
    ],
  },
  {
    id: "card_67",
    name: "Wheat Fields",
    suit: "economic",
    region: "herat",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["move", "gift"],
    effects: [],
  },
  {
    id: "card_68",
    name: "Ghaem Magham Farahani",
    suit: "intelligence",
    region: "persia",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax"],
    effects: [
      {
        id: "persian_influence",
        hook: "purchase",
        ruleText: "You do not pay for Persia cards in the market.",
      },
    ],
  },
  {
    id: "card_69",
    name: "Count Ivan Simonich",
    suit: "intelligence",
    region: "persia",
    coalition: "russian",
    rank: 2,
    stars: 0,
    isPatriot: true,
    actionIcons: ["battle", "move"],
    effects: [],
  },
  {
    id: "card_70",
    name: "Alexander Griboyedov",
    suit: "intelligence",
    region: "persia",
    coalition: "russian",
    rank: 2,
    stars: 0,
    isPatriot: true,
    actionIcons: ["move"],
    effects: [
      {
        id: "russian_influence",
        hook: "purchase",
        ruleText: "You do not pay for Russian Patriots in the market.",
      },
    ],
  },
  {
    id: "card_71",
    name: "Joseph Wolff",
    suit: "intelligence",
    region: "persia",
    coalition: "british",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["move", "gift"],
    effects: [],
  },
  {
    id: "card_72",
    name: "Claude Wade",
    suit: "intelligence",
    region: "persia",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["move"],
    effects: [
      {
        id: "safe_house",
        hook: "battle_resolution",
        ruleText: "When another player removes your spy in battle, you may place it on this card instead.",
      },
    ],
  },
  {
    id: "card_73",
    name: "Jean-François Allard",
    suit: "intelligence",
    region: "persia",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["build", "battle"],
    effects: [],
  },
  {
    id: "card_74",
    name: "Hajj Mirza Aghasi",
    suit: "political",
    region: "persia",
    coalition: "afghan",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["betray", "battle"],
    effects: [],
  },
  {
    id: "card_75",
    name: "Abbas Mirza",
    suit: "political",
    region: "persia",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "battle"],
    effects: [],
  },
  {
    id: "card_76",
    name: "Fath-Ali Shah",
    suit: "political",
    region: "persia",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: [],
    effects: [],
  },
  {
    id: "card_77",
    name: "Mohammad Shah",
    suit: "political",
    region: "persia",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["build", "betray"],
    effects: [],
  },
  {
    id: "card_78",
    name: "Civic Improvements",
    suit: "economic",
    region: "persia",
    coalition: "none",
    rank: 2,
    stars: 1,
    isPatriot: false,
    actionIcons: ["build"],
    effects: [
      {
        id: "infrastructure",
        hook: "build",
        ruleText: "After you take the build action, place one additional block in a legal space.",
      },
    ],
  },
  {
    id: "card_79",
    name: "Persian Slave Markets",
    suit: "economic",
    region: "persia",
    coalition: "none",
    rank: 1,
    stars: 1,
    isPatriot: false,
    actionIcons: ["tax", "move"],
    effects: [],
  },
  {
    id: "card_80",
    name: "Anglo-Persian Trade",
    suit: "economic",
    region: "persia",
    coalition: "british",
    rank: 1,
    stars: 1,
    isPatriot: true,
    actionIcons: ["tax", "build"],
    effects: [],
  },
  {
    id: "card_81",
    name: "Russo-Persian Trade",
    suit: "economic",
    region: "persia",
    coalition: "russian",
    rank: 2,
    stars: 1,
    isPatriot: true,
    actionIcons: ["tax", "build"],
    effects: [],
  },
  {
    id: "card_82",
    name: "Persian Army",
    suit: "military",
    region: "persia",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["gift", "battle"],
    effects: [],
  },
  {
    id: "card_83",
    name: "Shah's Guard",
    suit: "military",
    region: "persia",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax"],
    effects: [
      {
        id: "bodyguards",
        hook: "betray_protection",
        ruleText: "Your political cards cannot be targets of the betray action.",
      },
    ],
  },
  {
    id: "card_84",
    name: "Russian Regulars",
    suit: "military",
    region: "persia",
    coalition: "russian",
    rank: 2,
    stars: 0,
    isPatriot: true,
    actionIcons: ["battle"],
    effects: [],
  },
  {
    id: "card_85",
    name: "Bukharan Jews",
    suit: "intelligence",
    region: "transcaspia",
    coalition: "none",
    rank: 1,
    stars: 1,
    isPatriot: false,
    actionIcons: ["gift", "build"],
    effects: [],
  },
  {
    id: "card_86",
    name: "Jan Prosper Witkiewicz",
    suit: "intelligence",
    region: "transcaspia",
    coalition: "russian",
    rank: 2,
    stars: 0,
    isPatriot: true,
    actionIcons: ["move", "build"],
    effects: [],
  },
  {
    id: "card_87",
    name: "Imperial Surveyors",
    suit: "intelligence",
    region: "transcaspia",
    coalition: "russian",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["move", "gift", "build"],
    effects: [],
  },
  {
    id: "card_88",
    name: "Arthur Conolly",
    suit: "intelligence",
    region: "transcaspia",
    coalition: "british",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["move", "gift"],
    effects: [],
  },
  {
    id: "card_89",
    name: "Aga Mehdi",
    suit: "intelligence",
    region: "transcaspia",
    coalition: "russian",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["move", "betray", "battle"],
    effects: [],
  },
  {
    id: "card_90",
    name: "Nasrullah Khan",
    suit: "political",
    region: "transcaspia",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "betray"],
    effects: [],
  },
  {
    id: "card_91",
    name: "Allah Quli Bahadur",
    suit: "political",
    region: "transcaspia",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["betray"],
    effects: [
      {
        id: "savvy_operator",
        hook: "favored_suit",
        ruleText: "This card is always treated as if it were in the favored suit.",
      },
    ],
  },
  {
    id: "card_92",
    name: "Mir Murad Beg",
    suit: "political",
    region: "transcaspia",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle", "tax", "move"],
    effects: [],
  },
  {
    id: "card_93",
    name: "Madali Khan",
    suit: "political",
    region: "transcaspia",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["battle", "betray"],
    effects: [],
  },
  {
    id: "card_94",
    name: "Khivan Slave Markets",
    suit: "economic",
    region: "transcaspia",
    coalition: "none",
    rank: 1,
    stars: 1,
    isPatriot: false,
    actionIcons: ["tax", "betray"],
    effects: [],
  },
  {
    id: "card_95",
    name: "Supplies from Orenburg",
    suit: "economic",
    region: "transcaspia",
    coalition: "russian",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["tax", "move"],
    effects: [],
  },
  {
    id: "card_96",
    name: "Panjdeh Oasis",
    suit: "economic",
    region: "transcaspia",
    coalition: "none",
    rank: 2,
    stars: 0,
    isPatriot: false,
    actionIcons: ["tax", "move"],
    effects: [],
  },
  {
    id: "card_97",
    name: "The Ark of Bukhara",
    suit: "military",
    region: "transcaspia",
    coalition: "none",
    rank: 1,
    stars: 0,
    isPatriot: false,
    actionIcons: ["build"],
    effects: [
      {
        id: "citadel_transcaspia",
        hook: "battle_protection",
        ruleText: "Your tribes in Transcaspia cannot be attacked.",
      },
    ],
  },
  {
    id: "card_98",
    name: "European Cannons",
    suit: "military",
    region: "transcaspia",
    coalition: "none",
    rank: 3,
    stars: 0,
    isPatriot: false,
    actionIcons: ["gift"],
    effects: [],
  },
  {
    id: "card_99",
    name: "Cossacks",
    suit: "military",
    region: "transcaspia",
    coalition: "russian",
    rank: 1,
    stars: 0,
    isPatriot: true,
    actionIcons: ["battle"],
    effects: [
      {
        id: "irregulars",
        hook: "favored_suit",
        ruleText: "This card is always treated as if it were in the favored suit.",
      },
    ],
  },
  {
    id: "card_100",
    name: "Count Perovsky",
    suit: "military",
    region: "transcaspia",
    coalition: "russian",
    rank: 2,
    stars: 0,
    isPatriot: true,
    actionIcons: ["battle"],
    effects: [],
  },
];

export function validateCardLibrary(cards: CardDefinition[]): string[] {
  const issues: string[] = [];
  const seen = new Set<string>();
  for (const card of cards) {
    if (seen.has(card.id)) {
      issues.push(`Duplicate id: ${card.id}`);
    }
    seen.add(card.id);
    if (!card.name.trim()) {
      issues.push(`Card ${card.id} has empty name`);
    }
    if (card.rank < 1 || card.rank > 3) {
      issues.push(`Card ${card.id} rank out of range`);
    }
  }
  return issues;
}
